### ISSUE TITLE
Spaces in free-form comments

### ISSUE THREAD

**Issue by cocreature** [tdammers/yeshql#2]
Currently `yeshql` does not allow spaces in free-form comments since they are explicitly excluded https://github.com/tdammers/yeshql/blob/82f878fe120e69280a3154e197fba3da43016d61/src/Database/YeshQL/Parser.hs#L300. Is there some specific reason why this is the case? It seems like `manyTill anyChar newlineP` would work fine here.

**Comment by tdammers** [comment]
Hmm, that does look weird. Honestly though, I can't remember why I did this; I'd think that `manyTill anyChar newlineP` *should* be fine. I'll experiment a little, see if I can find an obvious reason.

**Comment by tdammers** [comment]
Can't really find a better explanation than this being a leftover from an early version of the syntax. Arbitrary characters in freeform docstrings make sense though, so I changed it.

**Comment by cocreature** [comment]
Thanks for the quick fix!
